### ISSUE TITLE
Confusion related to the Causal Cross Attention

### ISSUE THREAD

**Issue by arnavc1712** [floriankark/cs224n-win2223#5]
Hi, so in the Causal Cross Attention, I see we are registering a causal mask being the lower triangular matrix.
However when we are trying to learn the latent parameters C of seq_len m such that m < block_size. But the way it picks the mask seems weird, because it take the first m rows and columns based on the input sequence length.

For example lets say the mask for a block size of 5 is

False True  True   True   True
False False True   True   True
False False False  True   True
False False False  False  True
False False False  False  False

now lets say the C parameter we want to learn is of seq_len 2

Now given the line `att = att.masked_fill(self.mask[:,:,:Tq,:Tk] == 0, -1e10) `
where Tq=2 in our case and Tk=5

we get the mask as (first two rows and 5 columns)
False True  True   True   True
False False True   True   True

This mean we only take into account the first value vector to learn the first latent element and the first 2 value vectors to learn the second latent element. And disregard all the other value vectors.

Unless im understanding this incorrectly?

**Comment by floriankark** [comment]
Hi Arnav, sorry for the late reply! You're not misunderstanding it. 

I like to visualize this a little bit differently. In your example where Tq=2 and Tk=5 we get the masked attention (if we disregard B, nh for simplicity):
att[0,0] -1e10 -1e10 -1e10 -1e10 <- first k (or as you say value vector) to learn first q (or as you say latent element)
att[1,0] att[1,1] -1e10 -1e10 -1e10 <- first two k's to learn second q

This behavior is intentional because:
The sequence length of queries Tq is shorter than the full block size, and we only care about the causal constraints for the queries we are processing.
For learning the latent parameter C (sequence length Tq), the sliced mask ensures that only valid causal dependencies are considered, disregarding irrelevant key-value pairs.

Hope that clears the confusion by seeing this from a different perspective :)

**Comment by arnavc1712** [comment]
thanks for the answer!
However for a task such as neural machine translation, doesnt every query vector in the decoder pay attention to all the key/value vectors in the encoder? It seems as if we are limiting the key/value vectors in the encoder it can see when making a prediction, but in NMT it should be able to use all the key/value vectors right?

**Comment by floriankark** [comment]
Sure! 
Yes, every query vector pays attention to all key/value vectors. If not, then translation, e.g. german to english, would be hard because germans like to put verbs at the end which might not get picked up.
However, if q is 2 and k is 5, they would still have d_model 512 or 1024 or whatever you want which would then result in a matrix mult 2x512 * (5x512)^T so we get 2x5 for the attention scores. Thus, all 2 q's had access to all 5 k's. And after that we apply the mask.
Let me know if that helped :-)
